apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: habibaabdelgowad/notification-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: notification-service-config
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASS