apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
    spec:
      containers:
        - name: support-service
          image: habibaabdelgowad/support-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: support-service-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET