apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
      annotations:                   
        prometheus.io/scrape: "true"
        prometheus.io/port: "3005"
    spec:
      containers:
        - name: reporting-service
          image: habibaabdelgowad/reporting-service:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: reporting-service-config
          env:
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASS