apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
data:
  PORT: "3003"
  MONGODB_URI: "mongodb://mongodb:27017/ticket_db"
  NODE_ENV: "production"
  USER_SERVICE_URL: "http://user-service:4000"