#this file is for making the configuration of the nginx server to makie it 
# working as web server and in the same time reverse proxy 
# and the benefit of the reverse proxy that the frontend never has to know the internal ports of our backend services


server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # this line is critical for React Router to work
        # without it, refreshing any page gives 404
        try_files $uri $uri/ /index.html;
    }

    # proxy API calls to backend services
    # so frontend calls /api/users and nginx forwards to user-service
    location /api/users/ {
        proxy_pass http://user-service:4000/api/users/;
        proxy_set_header Host $host;
    }
/
    location /api/tickets/ {
        proxy_pass http://ticket-service:3003/api/tickets/;
        proxy_set_header Host $host;
    }

    location /api/support/ {
        proxy_pass http://support-service:3002/api/support/;
        proxy_set_header Host $host;
    }

    location /api/notifications/ {
         proxy_pass http://notification-service:3001/api/notifications/;
        proxy_set_header Host $host;
    }

    location /api/reports/ {
        proxy_pass http://reporting-service:3005/api/reports/;
        proxy_set_header Host $host;
    }
}